### PR TITLE
Updating release version

### PR DESCRIPTION
**Pull request by danielaRiesgo**
Made release and with that updated the version in README.

### CODE REVIEW

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Quality (Swiftlint): 100.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-reactive-core-ios/branches/development) for more details.

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Quality (Swiftlint): 100.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-reactive-core-ios/branches/downgrade-target) for more details.

**Comment by danielaRiesgo** [comment]
@DiegoQuiros94 please check this so we can merge it !

**Comment by woloxci** [comment]
**CodeStats metrics details:**

:white_check_mark: Code Quality (Swiftlint): 100.0


Click [here](http://codestats.wolox.com.ar/organizations/wolox/projects/wolmo-reactive-core-ios/branches/development) for more details.

**Pull request merged**
